data-gen:
    executable_path: /usr/local/bin/packer
    time: 10
    attack_machine_path: data_generation/virtual-machines/attack.ova
    target_machine_path: data_generation/virtual-machines/target.ova
    attack_username: root
    attack_password: yeet
    attack_ip: "192.168.0.14"
data-processing:
    dataset_path: data.csv
    filter: 
    filter_ip: "192.168.1.70" 
data-modeling:
    model_path: IDS.joblib
    image_path: tree.png
ids:
    model: intrusion_detection/IDS.joblib

